name: GitaWisdom
description: Gita Wisdom for Modern Day.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  supabase_flutter: ^2.9.1
  flutter_neumorphic: ^3.1.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.2.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0
  just_audio: ^0.10.4
  url_launcher: ^6.1.14
  intl: ^0.20.2  # or the latest version
  # firebase_core: any
 # firebase_analytics: any
dependency_overrides:
  win32: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.5.4
    # For app icons
  flutter_launcher_icons: ^0.14.4
  # Essential testing dependencies only
  mockito: ^5.4.5

  # Flutter Launcher Icons configuration
  gotrue: any
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_bg.png"
  adaptive_icon_background: "#FFFFFF"  # or use "assets/icon/bg.png"
  adaptive_icon_foreground: "assets/images/app_bg.png"
  image_path_ios: "assets/images/app_bg.png"
  remove_alpha_ios: true  # strips any transparency—required by App Store
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true  # Enable localization generation

  assets:
    - assets/images/divine_scroll_bg.png
    - assets/images/lotus.png
    - assets/images/lotus_bg.jpg
    - assets/audio/Riverside_Morning_Calm.mp3
    - assets/images/ow_hb.jpeg
    - assets/images/ow_app_hb.jp2
    - assets/images/app_bg.png
    - assets/images/hub4apps_qr.svg
    - assets/icons/
